/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

import java.util.*;
import java.time.*;

//Rappresenta un elemento di transizione tra i livelli, come una porta che si apre quando determinate condizioni sono soddisfatte
public class Door extends GameObject {

	public Door(int x, int y) {
		
		// TODO Auto-generated constructor stub
	}

}