/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

import java.util.*;
import javax.swing.*;
import java.awt.*;
import java.time.*;

//Gestisce la logica di gioco, inclusi il movimento dei personaggi, le collisioni e le interazioni di gioco.
public class GameEngine extends JFrame {
	
	public static void main(String[] args) {
		GameEngine f = new GameEngine();

	}
	public void init() {
		setLayout( new GridLayout(1,1,0,0));
		setLocationRelativeTo(null);
		InputManager s = new InputManager();
		setVisible(true);
	}

	public GameEngine() {
		super("UniPac-Man");
		setVisible(true);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setSize(500, 500);
		setLocation(200, 200);
		getContentPane().setBackground(Color.black);
		setResizable(false);
		init();

	}
	
}