/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/


import java.util.*;

import javax.imageio.ImageIO;

import java.io.IOException;

//fantasmini
public class Ghost extends Entity {
		GameEngine gp;
		
		public Ghost(GameEngine gp) {
			super(gp);
			name="fanstasma";
			direction="down";
			speed=1;
			solidArea.x=3;
			solidArea.y=7;
			solidArea.height=42;
			solidArea.width=30;
			solidAreaDefaultx = solidArea.x;
			solidAreaDefaulty = solidArea.y;
			
			getImage();
		}
		public void getImage() {
			try {
				imageGhost = ImageIO.read(getClass().getResourceAsStream("/pacman/fanstasmi/ROSSO.gif"));
			}catch(IOException e) {
				e.printStackTrace();
			}
		}
		public void setAction() {
			actionlockCounter++;
			if (actionlockCounter == 120) {
			     Random random = new Random();
			     int i = ((Random) random).nextInt(100)+1;
			     
			     if(i <= 25){
			        direction = "up";
			     }
			     if (i > 25 && i <= 50) {
			         direction = "down";
			     }
			     if (i > 50 && i <= 75) {
			        direction ="left";
			     }
			     if (i > 75 && i <= 100) {
			         direction = "right";
			     }
			     actionlockCounter = 0;

			 }
		}
}