/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

import java.util.*;
import java.time.*;

//Gestisce l'input dell'utente, come le pressioni dei tasti o i movimenti del mouse.
public class InputManager {

}