/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/


import java.util.*;
import java.time.*;

//Gestisce i livelli del gioco, inclusa la transizione tra di essi.

public class LevelManager {

}