/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

import java.util.*;
import java.time.*;

//Rappresenta un oggetto che conferisce al giocatore potenziamenti o benefici specifici quando raccolto
public class PowerUp extends GameObject {

	public PowerUp(int x, int y) {
		
		// TODO Auto-generated constructor stub
	}

}