/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

import java.util.*;
import java.time.*;

// Gestisce il punteggio del giocatore.
public class ScoreManager {

}