/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGMGoGlXmaEyoQ= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGMGoGlXmaEyoQ= >>
// ----------- >>
public class UniPacman{
// ----------- << class.extras@AAAAAAGMGoGlXmaEyoQ= >>
// ----------- >>
}