/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package oggetti;

import java.util.*;

import javax.imageio.ImageIO;

import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.time.*;

//Rappresenta un oggetto che conferisce al giocatore potenziamenti o benefici specifici quando raccolto
public class PowerUp extends GameObject {

	public PowerUp() {
		name="powerUp";
		try {
			powerUp=ImageIO.read(getClass().getResourceAsStream("/pacman/powerup/haivinto.png"));
		}catch(IOException e) {
			e.printStackTrace();
		}
		collision = true;
	}

}