/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package controller;


import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/*
 * Gestisce l'input dell'utente, come le pressioni dei tasti o i movimenti del mouse.
 * 
 */



public class InputManager implements  KeyListener {
	public static boolean upPressed;

	public static boolean downPressed;

	public static boolean leftPressed;

	public static boolean rightPressed;

// TODO Remove unused code found by UCDetector
// 	public static boolean spacePressed;

	private GameEngine gp;
	
	public InputManager(GameEngine gp) {
		this.gp=gp;
	}

	@Override
	public void keyTyped(KeyEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void keyPressed(KeyEvent e) {
		// TODO Auto-generated method stub
		int code = e.getKeyCode();

		
		if(gp.gameState == gp.titleState) {
			if(code == KeyEvent.VK_UP) {
				
				gp.ui.commandNum--;
				if(gp.ui.commandNum<0) {
					gp.ui.commandNum=1;
				}
			}
			if(code == KeyEvent.VK_LEFT) {
				gp.ui.commandNum++;
				if(gp.ui.commandNum>1) {
					gp.ui.commandNum=0;
				}
			}
			if (code == KeyEvent.VK_ENTER) {
				if(gp.ui.coommandNum==0) {
					gp.se.stop();
					gp.gameState = gp.playState;
				}
				if(gp.ui.commandNum==1) {
					System.exit(0);
				}
			}
		}

		//fine
		if(gp.gameState== gp.nextLevelState) {
			if (code == KeyEvent.VK_SPACE) {
				gp.gameState=gp.playState;
				gp.nextLevel();
			}
		}
		if(gp.gameState == gp.endState) {
			if (code == KeyEvent.VK_SPACE) {
				//gp.se.stop();
				gp.gameState=gp.titleState;
				gp.restart();
			}
		}


		if(code == KeyEvent.VK_UP) {
			upPressed = true;
		}
		if(code == KeyEvent.VK_DOWN) {
			downPressed = true;
		}
		if(code == KeyEvent.VK_LEFT) {
			leftPressed = true;
		}
		if(code == KeyEvent.VK_RIGHT) {
			rightPressed = true;
		}
		//tasto per la pausa
		if(code == KeyEvent.VK_P) {
			if(gp.gameState==gp.playState) {
				gp.gameState=gp.pauseState;
			}else if(gp.gameState==gp.pauseState) {
				gp.gameState=gp.playState;
			}
		}

	}

	@Override
	public void keyReleased(KeyEvent e) {
		// TODO Auto-generated method stub
		int code = e.getKeyCode();

		if(code == KeyEvent.VK_UP) {
			upPressed = false;
		}
		if(code == KeyEvent.VK_DOWN) {
			downPressed = false;
		}
		if(code == KeyEvent.VK_LEFT) {
			leftPressed = false;
		}
		if(code == KeyEvent.VK_RIGHT) {
			rightPressed = false;
		}
	}






}
