/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package view;


import java.awt.image.BufferedImage;


//Rappresenta un ostacolo o un elemento bloccante in un livello
public class Obstacole  {

	public BufferedImage image;
	public boolean collision = false;
	

}