/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package view;

import javax.imageio.ImageIO;
import java.io.IOException;

//Rappresenta un oggetto che conferisce al giocatore potenziamenti o benefici specifici quando raccolto
public class PowerUp extends GameObject {

	public PowerUp() {
		super("powerUp");
		try {
			powerUp=ImageIO.read(getClass().getResourceAsStream("/pacman/powerup/haivinto.png"));
		}catch(IOException e) {
			e.printStackTrace();
		}
		collision = true;
	}

}